### PR TITLE
Added jump search

### PR DESCRIPTION
**Pull request by Anjali2001saxena**

### CODE REVIEW

**Review by anku580 — CHANGES_REQUESTED** [review]
Since it is a search algorithm, can you please add in the searching folder?

**Comment by Anjali2001saxena** [comment]
Yes I will change the necessary.

**Comment by Anjali2001saxena** [comment]
I hope now it is fine, I have added jump search in searching folder.

**Review by anku580 — CHANGES_REQUESTED** [review]
Hi, can you remove the file jumsearch from algorithm folder? As you have already added in the searching folder.

**Review by anku580 — APPROVED** [review]

**Pull request merged**
