### PR TITLE
Added Algorithms

### PR DESCRIPTION
**Pull request by mohammadasad9450**
Added some sorting Algorithms

### CODE REVIEW

**Review by anku580 — CHANGES_REQUESTED** [review]
Can you create a folder name `Search` add all these files to it. After then, I will approve the PR.

Good job :clap:

**Comment by mohammadasad9450** [comment]
Bro I can make two
One for searching
and other for sorting
as I added algorithms for both
Please do accept

**Comment by mohammadasad9450** [comment]
Bro but how to crete folder

**Comment by anku580** [comment]
@mohammadasad9450 Since you have the forked repo in your machine. You can simply add the folder in your machine and then update the PR.

**Review by anku580 — APPROVED** [review]
Good one bro :clap:

**Comment by mohammadasad9450** [comment]
Thanku bro I am participating in hacktoberfest

**Comment by anku580** [comment]
All the best brother :+1:

You can connect with me on https://www.linkedin.com/in/anku580/

Also, if you find this repo worth, then you can `star` this repo.

**Comment by mohammadasad9450** [comment]
Bro please create another data structure repository of java and give me link

**Comment by mohammadasad9450** [comment]
bro i use whatsapp and facebook(little) or insta my brother uses no
linkedin I am in 10th grade

**Comment by anku580** [comment]
@mohammadasad9450 Why do you need another repository bro?

**Comment by mohammadasad9450** [comment]
Or can I create another pull request will that be counted in Hactoberfest

**Comment by mohammadasad9450** [comment]
Bro can u teach me about open source

**Comment by anku580** [comment]
@mohammadasad9450 You can use the same repo create multiple pull requests.

**Comment by mohammadasad9450** [comment]
Will that be counted in hacktoberfest

**Comment by mohammadasad9450** [comment]
Bro please merge my pull request one at 9:30 and another at 10 please sir
please do accept my request.

**Comment by mohammadasad9450** [comment]
Please  do accept #33 ASAP as I have to make more pull requests

**Pull request merged**
